### ISSUE TITLE
随机枚举应该如何实现

### ISSUE THREAD

**Issue by mumutu** [qiu8310/yod-mock#4]
谢谢0 0

**Comment by mumutu** [comment]
_.sample([1,2,3,4]) 实践是使用内置的函数么？

**Comment by qiu8310** [comment]
@Mumutu 

使用 `@([1,2,3,4]).sample`

解释下 `@([1,2,3,4])` 是创建一个数组，传任何东西给 `@()` 都会原样返回，然后就可以使用链式调用的形式对返回的对象进行处理

**Comment by mumutu** [comment]
好的 非常感谢！
